runtime: python39
entrypoint: uvicorn ingestion_api.main:app --host 0.0.0.0 --port $PORT

env_variables:
  NOMIC_INFERENCE_MODE: local
  ENVIRONMENT: production
  PYTHONPATH: /app

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 1

resources:
  cpu: 2
  memory_gb: 2 