steps:
  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'gcr.io/$PROJECT_ID/email-rag-backend:latest',
      '--tag', 'gcr.io/$PROJECT_ID/email-rag-backend:latest',
      '--tag', 'gcr.io/$PROJECT_ID/email-rag-backend:v1',
      '-f', 'Dockerfile.backend',
      '.'
    ]
  
  # Push the container image to Container Registry (us-central1)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/email-rag-backend:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/email-rag-backend:v1']
  
  # Deploy container image to Cloud Run in us-central1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'email-rag-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/email-rag-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NOMIC_INFERENCE_MODE=local,ENVIRONMENT=production'
      - '--cpu-throttling'
      - '--execution-environment'
      - 'gen2'

images:
  - 'gcr.io/$PROJECT_ID/email-rag-backend:latest'
  - 'gcr.io/$PROJECT_ID/email-rag-backend:v1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds
  diskSizeGb: '20'  # Optimized disk size
  # Note: Cloud Build always runs globally, but deployment is in us-central1 