name: Deploy to Cloud Run

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main ]

env:
  PROJECT_ID: emailrag99
  REGION: us-central1
  SERVICE_NAME: email-rag-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --region ${{ env.REGION }} \
          --project ${{ env.PROJECT_ID }} \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 1 \
          --min-instances 0 \
          --port 8080 \
          --timeout 300 \
          --concurrency 80 \
          --set-env-vars="NOMIC_INFERENCE_MODE=local,ENVIRONMENT=production" 